# Generated by Django 5.0.2 on 2024-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aadharimage', models.ImageField(upload_to='images/')),
                ('licenseimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
