# Generated by Django 5.0.3 on 2024-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_bikes_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='area',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='area',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
