# Generated by Django 5.0.3 on 2024-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_signup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='phoneno',
            field=models.CharField(default=6352176353, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='phoneno',
            field=models.CharField(default=6301538540, max_length=10),
            preserve_default=False,
        ),
    ]
