# Generated by Django 5.0.3 on 2024-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_bikes_phoneno_cars_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('describe', models.CharField(max_length=300)),
            ],
        ),
    ]
