# Generated by Django 5.0.3 on 2024-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='upload_by',
            field=models.CharField(default='srikanth0809', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='upload_by',
            field=models.CharField(default=123456789012345678901234567890, max_length=30),
            preserve_default=False,
        ),
    ]
